"""Fix order status default value and update existing records

Revision ID: fix_order_status_default
Revises: 94983354f88f
Create Date: 2025-11-20 10:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fix_order_status_default'
down_revision = '94983354f88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Update existing records with NULL status to 'pending'
    op.execute("UPDATE 'order' SET status = 'pending' WHERE status IS NULL")
    
    # For SQLite, we need to recreate the table with the default value
    # This is a workaround for SQLite's ALTER COLUMN limitations
    with op.batch_alter_table('order', schema=None) as batch_op:
        # SQLite doesn't support ALTER COLUMN to add default, so we'll just ensure data integrity
        pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # In downgrade, we don't need to do anything specific for SQLite
    pass
    # ### end Alembic commands ###